org.gradle.jvmargs=-Xmx4G

minecraft_version=1.20.1

archives_base_name=DeepMobLearningReloadedMod
mod_id=dmlreloaded
mod_version=3.0.1
maven_group=jp.artan

architectury_version=9.1.13

fabric_loader_version=0.15.6
fabric_api_version=0.91.1+1.20.1

forge_version=1.20.1-47.2.20

parchment_version=2023.09.03

is_local_artan_core=false
artan_core_local_version=4.0.1
artan_core_forge_version=5646913
artan_core_fabric_version=5646916

jei_api_version=15.3.0.4
jei_version=5576551

# https://github.com/VazkiiMods/Patchouli/tags
patchouli_version=1.20.1-81
# https://legacy.curseforge.com/minecraft/mc-mods/the-twilight-forest/files
twilight_forest_version=4.3.1850
# https://www.curseforge.com/minecraft/mc-mods/reliquary-reincarnations/files
reliquary_reincarnations=5253707
# https://www.curseforge.com/minecraft/mc-mods/official-divinerpg/files
divinerpg=5049334
# https://modmaven.dev/mekanism/Mekanism/
mekanism_version=5395221
mekanism_additions_version=5395223
mekanism_tools_version=5395225
mekanism_generators_version=5395224
# https://www.curseforge.com/minecraft/mc-mods/deeperdarker/files
deeper_and_darker=4807511
# https://maven.theillusivec4.top/top/theillusivec4/caelus/caelus-forge/
curios_version=5.3.5+1.20.1
# https://www.curseforge.com/minecraft/mc-mods/lionfish-api/files
lionfish_api_version=5363774
# https://www.curseforge.com/minecraft/mc-mods/lendercataclysm/files
lendercataclysm_version=5474791