org.gradle.jvmargs=-Xmx4G

minecraft_version=1.21.1

archives_base_name=DeepMobLearningReloadedMod
mod_id=dmlreloaded
mod_version=3.0.1
maven_group=jp.artan

architectury_version=13.0.6

fabric_loader_version=0.16.3
fabric_api_version=0.102.1+1.21.1

neoforge_version=21.1.57

parchment_version=2024.11.10
parchment_minecraft_version=1.21

jei_api_version=19.21.0.247
jei_version=5846880

# https://github.com/VazkiiMods/Patchouli/tags
patchouli_version=1.21-87
# https://legacy.curseforge.com/minecraft/mc-mods/the-twilight-forest/files
twilight_forest_version=4.6.2856
# https://www.curseforge.com/minecraft/mc-mods/reliquary-reincarnations/files
reliquary_reincarnations=5901305
# https://www.curseforge.com/minecraft/mc-mods/official-divinerpg/files
divinerpg=5049334
# https://modmaven.dev/mekanism/Mekanism/
mekanism_version=5395221
mekanism_additions_version=5395223
mekanism_tools_version=5395225
mekanism_generators_version=5395224
# https://www.curseforge.com/minecraft/mc-mods/deeperdarker/files
deeper_and_darker=5908863
# https://www.curseforge.com/minecraft/mc-mods/adorned/files
adorned_version=5740650
# https://www.curseforge.com/minecraft/mc-mods/lionfish-api/files
lionfish_api_version=5363774
# https://www.curseforge.com/minecraft/mc-mods/lendercataclysm/files
lendercataclysm_version=5474791