org.gradle.jvmargs=-Xmx1G

minecraft_version=1.19.2

archives_base_name=DeepMobLearningReloadedMod
mod_id=dmlreloaded
mod_version=3.0.0
maven_group=jp.artan

architectury_version=6.5.85

fabric_loader_version=0.15.3
fabric_api_version=0.77.0+1.19.2

forge_version=1.19.2-43.3.7

parchment_version=2022.08.14

is_local_artan_core=false
artan_core_local_version=4.0.1
artan_core_forge_version=5646912
artan_core_fabric_version=5646914

jei_api_version=11.5.0.297
jei_version=5543121

# https://github.com/VazkiiMods/Patchouli/tags
patchouli_version=1.19.2-77
# https://legacy.curseforge.com/minecraft/mc-mods/the-twilight-forest/files
twilight_forest_version=4.2.1518
# https://www.curseforge.com/minecraft/mc-mods/reliquary-reincarnations/files
reliquary_reincarnations=4666081
# https://www.curseforge.com/minecraft/mc-mods/official-divinerpg/files
divinerpg=4512117
# https://modmaven.dev/mekanism/Mekanism/
mekanism_version=4644795
mekanism_additions_version=4644797
mekanism_tools_version=4644799
mekanism_generators_version=4644798
# https://www.curseforge.com/minecraft/mc-mods/deeperdarker/files
deeper_and_darker=4812297
# https://maven.theillusivec4.top/top/theillusivec4/caelus/caelus-forge/
curios_version=1.19.2-5.1.4.1
