plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
}
architectury {
    platformSetupLoomIde()
    neoForge()
}
archivesBaseName = archives_base_name + "-neoforge-mc" + minecraft_version

sourceSets {
    main {
        resources.srcDir project(":common").file("src/main/generated")
    }
}
loom {
    runs {
        named("client") {
            setConfigName("${archives_base_name}-neoforge-Client")
        }
        named("server") {
            setConfigName("${archives_base_name}-neoforge-Server")
        }
        data {
            data()
            programArgs "--all", "--mod", "dmlreloaded"
            programArgs "--output", project(":common").file("src/main/generated").absolutePath
            setConfigName("${archives_base_name}-neoforge-Data")
            programArgs "--existing", project(":common").file("src/main/resources").absolutePath
        }
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

dependencies {
    neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"

    // Architectury API. This is optional, and you can comment it out if you don't need it.
    modImplementation "dev.architectury:architectury-neoforge:$rootProject.architectury_version"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionNeoForge")) { transitive = false }

    // JEI
    modCompileOnly "mezz.jei:jei-${minecraft_version}-forge-api:${jei_api_version}"
    modImplementation "curse.maven:jei-238222:${jei_version}"

    // Patchouli
    modCompileOnly "vazkii.patchouli:Patchouli:${patchouli_version}-NEOFORGE:api"
    modRuntimeOnly "vazkii.patchouli:Patchouli:${patchouli_version}-NEOFORGE"

    // Curios
    runtimeOnly "curse.maven:adorned-1036809:${adorned_version}"
    compileOnly "curse.maven:adorned-1036809:${adorned_version}"

    // Reliquary Reincarnations
    modImplementation "curse.maven:reliquary-241319:${reliquary_reincarnations}"

    // Deeper and Darker
    modImplementation "curse.maven:deeperdarker-659011:${deeper_and_darker}"

    // L_Ender 's Cataclysm
    // modImplementation "curse.maven:lionfish-1001614:${lionfish_api_version}"
    // modImplementation "curse.maven:lendercataclysm-551586:${lendercataclysm_version}"
    
    // ビルド時に不要なパッケージ

//    // The Twilight Forest
//    modImplementation "teamtwilight:twilightforest:${twilight_forest_version}:universal"
//
//    // DivineRPG
//    modImplementation "curse.maven:official-divinerpg-363543:${divinerpg}"
//
//    // Mekanism Additions
//    modImplementation "curse.maven:mekanism-268560:${mekanism_version}"             // core
//    modImplementation "curse.maven:mekanism-345425:${mekanism_additions_version}"   // Mekanism: Additions
//    modImplementation "curse.maven:mekanism-268566:${mekanism_generators_version}"  // Mekanism: Generators
//    modImplementation "curse.maven:mekanism-268567:${mekanism_tools_version}"       // Mekanism: Tools
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
    }
}

shadowJar {
    exclude "fabric.mod.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier.set("dev-shadow")
}

remapJar {
    inputFile.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier.set(null)
}

jar {
    archiveClassifier.set("dev")
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenNeoForge(MavenPublication) {
            artifactId = mod_id + "-" + project.name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
    }
}
